<a href="https://colab.research.google.com/github/MarioROT/CV-MAI/blob/main/Session%201/introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Computational Vision Lab 1
Students:
- Alam López
- Mario Rosas

# NumPy (Numerical Python)

NumPy works on **multidimensional homogeneous array objects** and it provides a collection of functions to process those arrays. NumPy is known for the fast numerical computations. Numpy provides a high level syntax and it has a very vibrant ecosystem that interopertes for different application areas. The n-dimensional arrays are known as **ndarray**. ndarray forms the primitive building blocks of numerous python libraries.

# Importing numpy

NumPy is available by default in Colab notebooks. Therefore the library can be invoked directly using the *import* statement

*PS: Follow the instructions on the [Installation section](https://numpy.org/install/) of NumPy to make local installations.*


In [1]:
import numpy as np
print("Loaded", np.__version__, "version of numpy!!!")

Loaded 1.23.5 version of numpy!!!


# Creating NumPy arrays

The basic ndarray is created using the **array** function, which takes any sequence as an input parameter. NumPy arrays can be easily created from lists


In [2]:
# creating a 1 dimensional array
var1 = np.array([1, 2, 3, 4, 5])

# creating a 2 dimensional array
var2 = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 0]])

print("var1 =", var1)
print("var2 =", var2)

var1 = [1 2 3 4 5]
var2 = [[1 2 3 4 5]
 [6 7 8 9 0]]


In [6]:
# It is also possible to specify the type of the element during array creation
var3 = np.array([1, 2, 3], dtype=np.float32)
print("var3 =", var3)

# Notice the usage of numpy arrays to create another array with a different dtype
var4 = np.array(var3, dtype=np.int32)
print("var4 =", var4)

var5 = np.array(var4, dtype=complex)
print("var5 =", var5)

var3 = [1. 2. 3.]
var4 = [1 2 3]
var5 = [1.+0.j 2.+0.j 3.+0.j]


# Array Properties
The important attributes of the ndarray are

*   shape: Dimensions of the array
*   size: Total number of elements in the array
*   ndim: Number of axes
*   dtype: Type of the elements of the array



In [7]:
print(var1.dtype, '\t', var1.shape, '\t', var1.size, '\t', var1.ndim)
print(var2.dtype, '\t', var2.shape, '\t', var2.size, '\t', var2.ndim)
print(var3.dtype, '\t', var3.shape, '\t', var3.size, '\t', var3.ndim)
print(var4.dtype, '\t', var4.shape, '\t', var4.size, '\t', var4.ndim)
print(var5.dtype, '\t', var5.shape, '\t', var5.size, '\t', var5.ndim)

int64 	 (5,) 	 5 	 1
int64 	 (2, 5) 	 10 	 2
float32 	 (3,) 	 3 	 1
int32 	 (3,) 	 3 	 1
complex128 	 (3,) 	 3 	 1


# Other array creation methods

It is not always necessary to have the elements defined during the creation of the arrays. There are several NumPy functions that allows you to create arrays to act as placeholders before the actual computations.

**Exercise #01:**

*   Create different array objects using the following functions: (1) zeros, (2) ones, (3) empty, (4) zeros_like, (5) ones_like, (6) empty_like


In [11]:
# Solution
#Zeros
var6 = np.zeros([1,3])
print('\n-- Zeros\n', var6)

# Ones
var7 = np.ones([3,1], dtype=np.float32)
print('\n-- Ones\n', var7)

# Empty
var8 = np.empty([3,3], dtype=np.int32)
print('\n-- Empty\n',var8)

#Zeros like
var9= np.zeros_like([2,3],dtype=np.int32)
print('\n-- Zeros like\n', var9)

# Ones like
var10 = np.ones_like([1,3])
print('\n-- Ones like\n', var10)

# Empty like
var11 = np.empty_like([3,3], dtype=np.float32)
print('\n-- Empty like\n',var11)


-- Zeros
 [[0. 0. 0.]]

-- Ones
 [[1.]
 [1.]
 [1.]]

-- Empty
 [[-871417456      22100          0]
 [         0        112          0]
 [ 678719340  691089970         48]]

-- Zeros like
 [0 0]

-- Ones like
 [1 1]

-- Empty like
 [1.e-45 0.e+00]


**Exercise #02:**

*   What is the difference between **empty** and **zeros** methods?
*   What is the use of **arange** and **linspace** functions?



**Solution**

- The **zeros** method returns and array with the specified shape and all values initialized to zero. On the other hand, the **empty** method returns also an array of the specified shape but, with uninitialized values (random initialization).


- The arrange and linspace functions are very similar. Both help us to create a sequence of numbers by defining the starting and finish points. The main difference is that wih **arrange**, we can define the *specific step* between one number and the next one, to get from the min to the max, while the **linspace** we can define how many values evenly spaced we want to have between the min and max.


# Shape Manipulations

In [19]:
# Creating a numpy array using arange function
var6 = np.arange(10, dtype=int)
print(var6, '\n')

# Reshaping the array into 2 x 5 array
var6 = var6.reshape(2,5)
print(var6, '\n')

# Reshaping the array in 3 dimensions
var6 = var6.reshape(1,2,5)
print(var6, '\n')

# Note that it is not always necessary to give all three dimensions
var6 = var6.reshape(1,2,-1)
print(var6)

[0 1 2 3 4 5 6 7 8 9] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[[0 1 2 3 4]
  [5 6 7 8 9]]] 

[[[0 1 2 3 4]
  [5 6 7 8 9]]]


**Exercise #03:**

*   What is the difference between reshape and resize methods?



**Solution**

When the **resize** and **reshape** methods are directly applied to the ndarray, **reshape** only takes comptible new shapes to transform the array, this means the same number of elements have to fit in the previous shape and in the new one. However, when the **resize** method is used, you can enter shapes with larger or smaller sizes, if it is larger it will fill with zeros the new spaces, if its smaller it will cut some of the elements.

...

# Indexing, Slicing and Iterating

Indexing and slicing is similar to python lists. We use the **[ ]** operator for providing slices and indices.

In [26]:
var7 = np.array([1, 2, 3, 4, 5])

# indexing the second element
# Remember array indices start with 0 in numpy
print(var7[1])

# slicing the first two elements of the array
print(var7[0:2])

2
[1 2]


In [29]:
# it is also possible to slice arrays based on a condition
print(var7[var7 % 2 == 0])  # prints all the even numbers in the array

[2 4]


In [34]:
var8 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(var8 , '\n')

# indexing the element at second row and second column
print(var8[1,1] , '\n')

# it is possible to slice the entire row or column
print(var8[1], '\n')
print(var8[:,1], '\n')

# slice a particular range
print(var8[0:2, 0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

5 

[4 5 6] 

[2 5 8] 

[[1 2]
 [4 5]]


A visual illustration of slicing mechanism can be seen here

![numpy_indexing.png](https://drive.google.com/uc?export=view&id=1y6rrsrihu3QS5_NGdYMo9mBnbv0qHehq)

*Reference: http://scipy-lectures.org*

**Exercise #04:**

*   What is the use of non-zero function? Provide an example of how non-zero function can be used.



**Solution**

The **nonzero** function returns the location (indices) of the values in the array that are different from zero. Indices are returned in a tuple of arrays, one for each dimension. If it is used to slice the same array you get the non-zero values directly if the transpose method is also used, you get an array per non-zero value with all indices for each.  

- This function can help when we are trying to perform some specific task only with the arrays that contain some data instead of all of them. We can easily keep only the ones that we really need to perform and threfore save some resouces.
...

In [ ]:
# solution

Iterating an array can be either performed using the python list style or using the nditer function.

In [44]:
var9 = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])

for i in var9: # outer loop to access row
    print(i) # returs the entire row

for i in var9: # outer loop to access row
    for j in i:  # iterating each element of the row
        print(j) # returs the element value

[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9


In [41]:
# an alternative to the nesting for loop is the nditer function
var10 = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
for i in np.nditer(var10):
    print(i)

1
2
3
4
5
6
7
8
9


**Exercise #05:**

*   How can we enumerate a numpy array?



**Solution**

There are multiple approaches to anumerate an array. However in all of them we need o  use an iteration in order to make it general for any array.

We can set a index = 0, and for each value inside the array we add 1 to the current index.

It has to be noted that, slices share memory with original array.

In the below example, var12 is created by slicing var11. Notice the change in var11 after modifying var12.

In [49]:
var11 = np.array([1, 2, 3])
print(var11,'\n')

var12 = var11[0:1]
print(var12,'\n')

print('before changing:', var11)

var12[0] = 4

print('after changing:', var11)

[1 2 3] 

[1] 

before changing: [1 2 3]
after changing: [4 2 3]


This leaves us with the question of how the array copy works in numpy

# Array Copy

When you create a new array using the '=' operator, no new copy of the array is created, ie, only a name is created but it refers to the same object.

In [50]:
var13 = np.array([1, 2, 3, 4, 5])

var14 = var13
print('Before modifying', var13)

var14[0] += 1
print('After modifying', var13)

Before modifying [1 2 3 4 5]
After modifying [2 2 3 4 5]


When a view function is used to create a copy of the array, or when the array is sliced, the returned array is only a shallow copy of the original array, ie, an array object is created but the object points to the same data

In [51]:
var15 = np.array([1, 2, 3, 4, 5])

var16 = var15.view()
print('Before modifying (using view)', var15)

var16[0] += 1
print('After modifying (using view)', var15)

var17 = var15[0:3]
print('Before modifying (using slice)', var15)

var17[2] += 1
print('After modifying (using slice)', var15)

Before modifying (using view) [1 2 3 4 5]
After modifying (using view) [2 2 3 4 5]
Before modifying (using slice) [2 2 3 4 5]
After modifying (using slice) [2 2 4 4 5]


To create a deep copy of the array, it is necessary to use the copy method

In [52]:
var18 = np.array([1, 2, 3, 4, 5])

var19 = var18.copy()
print('Before modifying (using copy)', var18)

var19[0] += 1
print('After modifying (using copy)', var18)

Before modifying (using copy) [1 2 3 4 5]
After modifying (using copy) [1 2 3 4 5]


# Adding new axis

It is also possible to increase the dimensions of a numpy array. **np.newaxis** and **expand_dims** can be used to increase the dimensions of the array. This would be used very handy in building convolutional neural networks where you would need to have uniform channel lengths *(will be used in the later exercises)*.

In [53]:
var20 = np.array([1, 2, 3, 4, 5])
print(var20.shape)

a = var20[np.newaxis, :]  # adding new axis to the first axis
print(a.shape)

b = a[np.newaxis, :]  # adding new axis to the first axis
print(b.shape)

c = np.expand_dims(var20, axis=1)  # adding new axis to the second axis
print(c.shape)

d = np.expand_dims(var20, axis=0)  # adding new axis to the first axis
print(d.shape)

(5,)
(1, 5)
(1, 1, 5)
(5, 1)
(1, 5)


# Broadcasting Rules

Broadcasting deals with how numpy treats arrays with different sizes during arithmetic operations. In general, the smaller arrays are broadcasted into the larger array shapes so that both the arrays are compatible.

Read [basic broadcasting rules](https://numpy.org/doc/stable/user/basics.broadcasting.html) for basic knowledge about broadcasting.
Also read [Array broadcasting](https://numpy.org/doc/stable/user/theory.broadcasting.html#array-broadcasting-in-numpy).


In [55]:
var20 = np.array([[1.2, 2.3, 4.0],
                  [1.2, 3.4, 5.2],
                  [0.0, 1.0, 1.3],
                  [0.0, 1.0, 2e-1]])

print(var20,'\n')

print(var20 * 2,'\n')  # multiplying each element with 2

print(var20 + [1, 0, 1])  # adding each row with [1, 0, 1]]

[[1.2 2.3 4. ]
 [1.2 3.4 5.2]
 [0.  1.  1.3]
 [0.  1.  0.2]] 

[[ 2.4  4.6  8. ]
 [ 2.4  6.8 10.4]
 [ 0.   2.   2.6]
 [ 0.   2.   0.4]] 

[[2.2 2.3 5. ]
 [2.2 3.4 6.2]
 [1.  1.  2.3]
 [1.  1.  1.2]]


**Exercise #06:**

Normalizing values is an important area in any image processing and machine learning problem. In this exercise, we will try to apply normalization at different axis to understand the role of broadcasting.

In [77]:
var21 = np.array([[1.2, 2.3, 4.0],
                  [1.2, 3.4, 5.2],
                  [0.0, 1.0, 1.3],
                  [0.0, 1.0, 2e-1]])
print('Original\n',var21,'\n' )

# compute row wise mean
var21_mean_row = var21.mean(1)   # code fill up
print('Row Wise Mean\n',var21_mean_row,'\n')

# compute column wise mean
var21_mean_clm = var21.mean(0)  # code fill up
print('Column Wise Mean\n',var21_mean_clm,'\n')

# do row wise mean subtraction and column wise mean subtraction
# solution¨
var21_rwms=np.transpose(np.transpose(var21)-np.transpose(var21_mean_row) )
print('Row Mean Substraction \n',var21_rwms,'\n')

var21_cwms=var21-var21_mean_clm
print('Column Mean Substraction \n',var21_cwms,'\n')
# how do we normalize the entire array using the global mean?
# solution




Original
 [[1.2 2.3 4. ]
 [1.2 3.4 5.2]
 [0.  1.  1.3]
 [0.  1.  0.2]] 

Row Wise Mean
 [2.5        3.26666667 0.76666667 0.4       ] 

Column Wise Mean
 [0.6   1.925 2.675] 

Row Mean Substraction 
 [[-1.3        -0.2         1.5       ]
 [-2.06666667  0.13333333  1.93333333]
 [-0.76666667  0.23333333  0.53333333]
 [-0.4         0.6        -0.2       ]] 

Column Mean Substraction 
 [[ 0.6    0.375  1.325]
 [ 0.6    1.475  2.525]
 [-0.6   -0.925 -1.375]
 [-0.6   -0.925 -2.475]] 





*   Can you think of an example of row wise normalization and column wise normalization?



**Solution**

- **Row wise normalization** can be used when you want to perform instance normalization, so between the values of a given instance of your dataset, this becomes useful for some techniques used in specific layers for convolutional networks known as normalization layers, a common type of normalization used is instance normalization, where this type of normalization can be applied.


- **Column wise normalization** in the same way can be used to perform some standardization the input of a training data set for Neural Networks.




---


**It has to be noted that this is not a complete tutorial covering the complete numpy aspects. This is provided as an introduction to numpy and its ease of use in numerical computation.**